baseURL = 'https://armedexterminators.net/'
languageCode = 'en-us'

title = "Pest Control Pasadena, CA | Armed Exterminators"
description= "Need an exterminator in Pasadena? Family‑owned Armed Exterminators removes rats, ants, roaches, spiders & wildlife. Call (626) 256-3200."
